version: "3"
services:
  mongo:
    image: mongo:6
    ports:
      - "30000:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  import-script:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    depends_on:
      - mongo
    volumes:
      - ./scripts:/app/scripts
    environment:
      - MONGO_URL=mongodb://mongo:27017/HelsinkiBikeApp  
    command: sh -c "node ./scripts/import.js"
    networks:
      - backend-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"  
    depends_on:
      - import-script
    volumes:
      - ./scripts:/app/scripts
    environment:
      - MONGO_URL=mongodb://mongo:27017/HelsinkiBikeApp
    command: sh -c "sleep 30 && npm run start"
    networks:
      - backend-network

  frontend:
    build:
      context: ./react-client
      dockerfile: Dockerfile.reactApp
    depends_on:
      - import-script
    ports:
      - "5000:5000"
    command: sh -c "sleep 30 && npm run dev"
    networks:
      - backend-network
      - frontend-network

networks:
  backend-network:
  frontend-network:
volumes:
  mongo-data: